DOMAIN = "urdash"
PANEL_URL = "urdash"
PANEL_TITLE = "UrDash"
PANEL_ICON = "mdi:card-plus-outline"
FRONTEND_DIR = "frontend"
FRONTEND_JS = "urdash-panel.js"
FRONTEND_VERSION = "20260712.2"
STATIC_URL = f"/{DOMAIN}/static"

DEFAULT_THEME = "aurora"
DEFAULT_HEIGHT_MODE = "auto"
DEFAULT_OPENAI_MODEL = "gpt-5.2"
DEFAULT_OPENAI_BASE_URL = "https://api.openai.com/v1"

CONF_API_KEY = "api_key"
CONF_MODEL = "model"
CONF_BASE_URL = "base_url"
CONF_DEFAULT_THEME = "default_theme"
CONF_DEFAULT_HEIGHT_MODE = "default_height_mode"

AI_PROVIDER_OPENAI = "openai"
